### ISSUE TITLE
pipam.github.io gives 404

### ISSUE THREAD

**Issue by probonopd** [pipam/pipam#1]
https://pipam.github.io/ is linked from the README.md but gives error 404

**Comment by facekapow** [comment]
First, thanks for taking an interest in pipam! Second, I still haven't published the website because I'm still trying to work out the problems with continuous deployment with Linux on Travis. I will be pushing it out soon, though!

**Comment by probonopd** [comment]
Looking forward to it, especially your use of AppImage.

**Comment by facekapow** [comment]
Should be fixed, just pushed up the website!
